name: Build Tun2Socks AAR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-aar:
    name: Build AAR with gomobile
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        export PATH=$HOME/go/bin:$PATH
        gomobile init

    - name: Build AAR for all ABIs
      run: |
        export PATH=$HOME/go/bin:$PATH
        gomobile bind -target=android/arm64,android/arm,android/386,android/amd64 \
                      -o tun2socks.aar ./mobile

    - name: Upload AAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: tun2socks-aar
        path: tun2socks.aar
