name: Build Tun2Socks AAR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-aar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.11' # Go >= 1.23 是 gomobile 的要求

    - name: Set up Android SDK + NDK
      uses: android-actions/setup-android@v3

    - name: Install NDK 25.2.9519653
      run: |
        yes | sdkmanager --install "ndk;25.2.9519653"
        echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV

    - name: Install gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        export PATH=$HOME/go/bin:$PATH
        gomobile init

    - name: Build AAR
      run: |
        export PATH=$HOME/go/bin:$PATH
        export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.2.9519653
        gomobile bind -target=android/arm64,android/arm,android/386,android/amd64 \
                      -o tun2socks.aar ./mobile

    - name: Upload AAR
      uses: actions/upload-artifact@v4
      with:
        name: tun2socks-aar
        path: tun2socks.aar
